% Build the Simulink model gfl_10kva_lcl.slx in the folder of this script.
% Generated by motulator_export.simulink from motulator. The parameters of
% the control system are in the mask of the subsystem 'Grid-following control',
% and those of the system model in the model workspace.
%
% The S-function sfun_grid_following_control.c is compiled with mex, which needs a C99
% compiler with complex.h (gcc, clang, or MinGW-w64, not MSVC), see
% mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_export', 'simulink'));

s = struct();
s.folder = here;
s.name = 'gfl_10kva_lcl';
s.init = strjoin({ ...
    'converter.u_dc = 650.0;', ...
    'ac_filter.L_fc = 0.003700874424440534;', ...
    'ac_filter.L_fg = 0.003700874424440534;', ...
    'ac_filter.C_f = 8.593839157387184e-06;', ...
    'ac_filter.u_f0_ab = [326.5986323710904 0.0];', ...
    'ac_source.e_g = 326.5986323710904;', ...
    'ac_source.w_g = 314.1592653589793;'}, newline);
s.ac_filter = 'lcl';
s.refs = { ...
    'enable', 'constant', 1.0
    'p_g_ref', 'step', [0.020050000000000002 0.0 5000.0]
    'q_g_ref', 'step', [0.03995 0.0 4000.0]
    };
s.scope = { ...
    'Power', [7.0 8.0 9.0 10.0]
    'Converter current', [1.0 2.0 3.0]
    'Current', [11.0 12.0 13.0 14.0]
    'PLL', [15.0 16.0 17.0]
    };
s.control.name = 'Grid-following control';
s.control.sfunction = 'sfun_grid_following_control';
s.control.mask_type = 'Grid-following control (motulator)';
s.control.description = 'Current-vector grid-following control with a PLL in the power-control mode. The parameters correspond to the motulator API: CurrentVectorControllerCfg. Empty parameters ([]) correspond to the defaults of motulator. While the input enable is not positive, the duty ratios are 0.5 and the state is reset to its initial value.';
s.control.mask = { ...
    'i_max', 'Maximum current (A), peak value: i_max', 'Grid-following control (CurrentVectorControllerCfg)', '30.75914498161482'
    'L', 'Filter inductance (H): L', 'Grid-following control (CurrentVectorControllerCfg)', '0.003700874424440534'
    'alpha_c', 'Current-control bandwidth (rad/s): alpha_c', 'Grid-following control (CurrentVectorControllerCfg)', '2*pi*400'
    'alpha_i', 'Integral-action bandwidth (rad/s), [] = alpha_c: alpha_i', 'Grid-following control (CurrentVectorControllerCfg)', '2*pi*400'
    'u_nom', 'Nominal grid voltage (V), peak phase: u_nom', 'Grid-following control (CurrentVectorControllerCfg)', '326.5986323710904'
    'w_nom', 'Nominal grid angular frequency (rad/s): w_nom', 'Grid-following control (CurrentVectorControllerCfg)', '2*pi*50'
    'alpha_pll', 'PLL bandwidth (rad/s): alpha_pll', 'Grid-following control (CurrentVectorControllerCfg)', '2*pi*20'
    'T_s', 'Sampling period (s): T_s', 'Grid-following control (CurrentVectorControllerCfg)', '0.0001'
    };
s.control.mask_init = '';
s.control.params = {'double(i_max)', 'double(L)', 'double(alpha_c)', 'double(alpha_i)', 'double(u_nom)', 'double(w_nom)', 'double(alpha_pll)', 'double(T_s)'};
s.control.inputs = {'enable', 'p_g_ref', 'q_g_ref', 'i_c_abc', 'u_g_line', 'u_dc'};
s.control.outputs = {'d_abc', 'Power (p_g_ref, p_g, q_g_ref, q_g)', 'Current (i_c_d_ref, i_c_d, i_c_q_ref, i_c_q)', 'PLL (u_g, w_g, theta_c)'};
s.T_s = 0.0001;
s.t_stop = 0.08;

build_grid(s);
