% Build the Simulink model gfm_13kva_do.slx in the folder of this script.
% Generated by motulator_export.simulink from motulator. The parameters of
% the control system are in the mask of the subsystem 'Grid-forming control',
% and those of the system model in the model workspace.
%
% The S-function sfun_grid_forming_control.c is compiled with mex, which needs a C99
% compiler with complex.h (gcc, clang, or MinGW-w64, not MSVC), see
% mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_export', 'simulink'));

s = struct();
s.folder = here;
s.name = 'gfm_13kva_do';
s.init = strjoin({ ...
    'converter.u_dc = 650.0;', ...
    'ac_filter.L_f = 0.006125876615797688;', ...
    'ac_filter.R_f = 0.6415002990995841;', ...
    'ac_filter.L_g = 0.030220991304601926;', ...
    'ac_source.e_g = 326.5986323710904;', ...
    'ac_source.w_g = 314.1592653589793;'}, newline);
s.ac_filter = 'l';
s.refs = { ...
    'enable', 'constant', 1.0
    'p_g_ref', 'step', [0.2000625 0.0 4166.666666666667; 0.5000625 0.0 4166.666666666667; 0.7999375 0.0 4166.666666666666; 1.1999375 0.0 -25000.0]
    'v_c_ref', 'constant', 326.5986323710904
    };
s.scope = { ...
    'Power', [4.0 5.0 6.0]
    'Converter current', [1.0 2.0 3.0]
    'Voltage', [7.0 8.0]
    'Current', [9.0 10.0 11.0 12.0]
    'Angle', [13.0]
    };
s.control.name = 'Grid-forming control';
s.control.sfunction = 'sfun_grid_forming_control';
s.control.mask_type = 'Grid-forming control (motulator)';
s.control.description = 'Disturbance-observer-based grid-forming control in the power-control mode, with transparent current limitation. The parameters correspond to the motulator API: ObserverBasedGridFormingControllerCfg. Empty parameters ([]) correspond to None, i.e., the defaults of motulator. While the input enable is not positive, the duty ratios are 0.5 and the state is reset to its initial value.';
s.control.mask = { ...
    'i_max', 'Maximum current (A), peak value: i_max', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '33.09259735953043'
    'L', 'Total inductance estimate (H): L', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '0.014293712103527936'
    'R', 'Total series resistance estimate (Ohm): R', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '0.6415002990995841'
    'R_a', 'Active resistance (Ohm), [] = 0.25*u_nom/i_max: R_a', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '2.5660011963983362'
    'k_v', 'Voltage control gain, [] = alpha_o/w_nom: k_v', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '[]'
    'alpha_o', 'Observer gain (rad/s): alpha_o', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '2*pi*50'
    'alpha_c', 'Current-control bandwidth (rad/s): alpha_c', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '2*pi*400'
    'u_nom', 'Nominal grid voltage (V), peak phase: u_nom', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '326.5986323710904'
    'w_nom', 'Nominal grid angular frequency (rad/s): w_nom', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '2*pi*50'
    'T_s', 'Sampling period (s): T_s', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '0.000125'
    'i_d_max', 'Maximum active current (A), [] = no power limitation: i_d_max', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '[]'
    'alpha_l', 'Power-limitation bandwidth (rad/s): alpha_l', 'Grid-forming control (ObserverBasedGridFormingControllerCfg)', '2*pi*50'
    };
s.control.mask_init = '';
s.control.params = {'double(i_max)', 'double(L)', 'double(R)', 'double(R_a)', 'double(k_v)', 'double(alpha_o)', 'double(alpha_c)', 'double(u_nom)', 'double(w_nom)', 'double(T_s)', 'double(i_d_max)', 'double(alpha_l)'};
s.control.inputs = {'enable', 'p_g_ref', 'v_c_ref', 'i_c_abc', 'u_dc'};
s.control.outputs = {'d_abc', 'Power (p_g_ref, p_g, q_g)', 'Voltage (v_c_ref, v_c)', 'Current (i_c_d_ref, i_c_d, i_c_q_ref, i_c_q)', 'Angle (theta_c)'};
s.T_s = 0.000125;
s.t_stop = 1.4;

build_grid(s);
