% Build the Simulink library im_2kw_cvc_control.slx in the folder of this script.
% Generated by motulator_export.simulink from motulator. The library
% contains the control system 'Current-vector control', whose parameters
% are in the mask of the subsystem.
%
% The S-function sfun_im_2kw_cvc_control.c is compiled with mex, which needs a C99
% compiler with complex.h (gcc, clang, or MinGW-w64, not MSVC), see
% mex -setup C.

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, '..', '..', 'motulator_export', 'simulink'));

s = struct();
s.folder = here;
s.name = 'im_2kw_cvc_control';
s.control.name = 'Current-vector control';
s.control.sfunction = 'sfun_im_2kw_cvc_control';
s.control.mask_type = 'Current-vector control (motulator)';
s.control.description = 'Speed control of an induction machine drive with current-vector control. The parameters correspond to the motulator API: InductionMachineInvGammaPars, CurrentVectorControllerCfg, and SpeedController. Empty parameters ([]) correspond to None, i.e., the defaults of motulator. While the input enable is not positive, the duty ratios are 0.5 and the state is reset to its initial value.';
s.control.mask = { ...
    'n_p', 'n_p: Number of pole pairs', 'Machine model (InductionMachineInvGammaPars)', '2.0'
    'R_s', 'R_s: Stator resistance (Ohm)', 'Machine model (InductionMachineInvGammaPars)', '3.7'
    'R_R', 'R_R: Rotor resistance (Ohm)', 'Machine model (InductionMachineInvGammaPars)', '2.1'
    'L_sgm', 'L_sgm: Leakage inductance (H)', 'Machine model (InductionMachineInvGammaPars)', '0.021'
    'L_M', 'L_M: Magnetizing inductance (H)', 'Machine model (InductionMachineInvGammaPars)', '0.224'
    'psi_s_nom', 'psi_s_nom: Nominal stator flux linkage (Vs)', 'Current-vector control (CurrentVectorControllerCfg)', '1.0395957349782348'
    'i_s_max', 'i_s_max: Maximum stator current (A)', 'Current-vector control (CurrentVectorControllerCfg)', '10.606601717798213'
    'alpha_c', 'alpha_c: Current-control bandwidth (rad/s)', 'Current-vector control (CurrentVectorControllerCfg)', '2*pi*200'
    'alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_c', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'alpha_o', 'alpha_o: Speed estimation pole (rad/s), [] = default', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'w_s_nom', 'w_s_nom: Nominal stator angular frequency (rad/s)', 'Current-vector control (CurrentVectorControllerCfg)', '2*pi*50'
    'k_u', 'k_u: Voltage utilization factor', 'Current-vector control (CurrentVectorControllerCfg)', '0.95'
    'k_fw', 'k_fw: Field-weakening gain (1/H), [] = default', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'J', 'J: Inertia (kgm^2) for the speed observer, [] = not used', 'Current-vector control (CurrentVectorControllerCfg)', '[]'
    'sensorless', 'sensorless: Sensorless mode (1) or sensored mode (0)', 'Current-vector control (CurrentVectorControllerCfg)', '1.0'
    'T_s', 'T_s: Sampling period (s)', 'Current-vector control (CurrentVectorControllerCfg)', '0.000125'
    'speed_J', 'J: Total inertia (kgm^2)', 'Speed control (SpeedController)', '0.015'
    'speed_alpha_s', 'alpha_s: Reference-tracking bandwidth (rad/s)', 'Speed control (SpeedController)', '2*pi*4'
    'speed_alpha_i', 'alpha_i: Integral-action bandwidth (rad/s), [] = alpha_s', 'Speed control (SpeedController)', '[]'
    'speed_tau_M_max', 'tau_M_max: Maximum motor torque (Nm)', 'Speed control (SpeedController)', 'inf'
    'pwm_t_d', 't_d: Dead time (s) in d_err = dead_time_error(i_abc, d_abc, t_d, T_s), 0 = None', 'PWM (PWM)', '0.0'
    'pwm_feedforward', 'feedforward: Compensate for d_err (1) or not (0)', 'PWM (PWM)', '1.0'
    };
s.control.mask_init = '';
s.control.params = {'double(n_p)', 'double(R_s)', 'double(R_R)', 'double(L_sgm)', 'double(L_M)', 'double(psi_s_nom)', 'double(i_s_max)', 'double(alpha_c)', 'double(alpha_i)', 'double(alpha_o)', 'double(w_s_nom)', 'double(k_u)', 'double(k_fw)', 'double(J)', 'double(sensorless)', 'double(T_s)', 'double(speed_J)', 'double(speed_alpha_s)', 'double(speed_alpha_i)', 'double(speed_tau_M_max)', 'double(pwm_t_d)', 'double(pwm_feedforward)'};
s.control.inputs = {'enable', 'w_M_ref', 'i_s_abc', 'u_dc', 'w_M'};
s.control.outputs = {'d_abc', 'Speed (w_M_ref, w_M)', 'Torque (tau_M_ref, tau_M)', 'Flux linkage (psi_s, psi_R)', 'Current (i_sd_ref, i_sd, i_sq_ref, i_sq)'};

build_control(s);
