/*
 * sfun_grid_following_control: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_grid_following_control.c
 */

#define S_FUNCTION_NAME sfun_grid_following_control
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export.plecs.grid. The control algorithms are in
 * the included C files. The parameters come from the mask of the
 * subsystem. */
#include "common.c"
#include "gfl_current_vector.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Lower limit (V) of the measured DC-bus voltage, which avoids the division by
 * zero in the PWM if the DC bus is not charged */
#define U_DC_MIN 1.0

static GFLControlSystem ctrl;

/* Initial state, restored while the control system is disabled */
static GFLControlSystem ctrl_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 1, 1, 3, 2, 1};
static const int FEEDTHROUGH[] = {1, 1, 1, 1, 1, 1};
static const int OUTPUT_WIDTHS[] = {3, 4, 4, 3};
#define NUM_INPUTS 6
#define NUM_OUTPUTS 4
#define NUM_PARAMS 8

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(7, 0) * ParamDim(7, 1) != 1
        || !(ParamRealData(7, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(7, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    /* Check the parameters of the mask */
    if (PDIM(0) != 1) {
        SetErrorMessage("i_max must be a scalar.");
        return;
    }
    if (PDIM(1) != 1) {
        SetErrorMessage("L must be a scalar.");
        return;
    }
    if (PDIM(7) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }

    /* Configuration (CurrentVectorControllerCfg), the defaults are used for
     * empty parameters */
    GFLControllerCfg cfg = gfl_controller_cfg(P(0, 0), P(1, 0));
    if (PDIM(2) > 0) {
        cfg.alpha_c = P(2, 0);
    }
    if (PDIM(4) > 0) {
        cfg.u_nom = P(4, 0);
    }
    if (PDIM(5) > 0) {
        cfg.w_nom = P(5, 0);
    }
    if (PDIM(6) > 0) {
        cfg.alpha_pll = P(6, 0);
    }
    if (PDIM(7) > 0) {
        cfg.T_s = P(7, 0);
    }
    cfg.alpha_i = PDIM(3) > 0 ? P(3, 0) : cfg.alpha_c;
    gfl_control_system_init(&ctrl, &cfg);

    ctrl_init = ctrl;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: zero voltage, the control algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 3; k++) {
            OutputSignal(0, k) = 0.5;
        }
        OutputSignal(1, 0) = 0.0;
        OutputSignal(1, 1) = 0.0;
        OutputSignal(1, 2) = 0.0;
        OutputSignal(1, 3) = 0.0;
        OutputSignal(2, 0) = 0.0;
        OutputSignal(2, 1) = 0.0;
        OutputSignal(2, 2) = 0.0;
        OutputSignal(2, 3) = 0.0;
        OutputSignal(3, 0) = 0.0;
        OutputSignal(3, 1) = 0.0;
        OutputSignal(3, 2) = 0.0;
        return;
    }

    /* Measurements and references */
    double i_c_abc[3] = {InputSignal(3, 0), InputSignal(3, 1),
                         InputSignal(3, 2)};
    /* Line-to-line PCC voltages u_ab and u_bc */
    double u_g_line[2] = {InputSignal(4, 0), InputSignal(4, 1)};
    double u_dc = fmax(InputSignal(5, 0), U_DC_MIN);
    GridMeasurements meas = {abc2complex(i_c_abc), line2complex(u_g_line),
                             u_dc};
    gfl_control_system_compute_output(&ctrl, &meas, InputSignal(1, 0),
                                      InputSignal(2, 0));

    /* Duty ratios, delayed by the Delay block outside the subsystem */
    for (int k = 0; k < 3; k++) {
        OutputSignal(0, k) = ctrl.ref.d_abc[k];
    }

    /* Monitored signals */
    OutputSignal(1, 0) = ctrl.ref.p_g;
    OutputSignal(1, 1) = ctrl.fbk.p_g;
    OutputSignal(1, 2) = ctrl.ref.q_g;
    OutputSignal(1, 3) = ctrl.fbk.q_g;
    OutputSignal(2, 0) = creal(ctrl.ref.i_c);
    OutputSignal(2, 1) = creal(ctrl.fbk.i_c);
    OutputSignal(2, 2) = cimag(ctrl.ref.i_c);
    OutputSignal(2, 3) = cimag(ctrl.fbk.i_c);
    OutputSignal(3, 0) = ctrl.fbk.u_g;
    OutputSignal(3, 1) = ctrl.fbk.w_g;
    OutputSignal(3, 2) = ctrl.fbk.theta_c;
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        ctrl = ctrl_init;
        return;
    }

    gfl_control_system_update(&ctrl);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
