/*
 * sfun_current_vector_control: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex -I<motulator_export/c> sfun_current_vector_control.c
 */

#define S_FUNCTION_NAME sfun_current_vector_control
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export.plecs.im. The control algorithms are in the
 * included C files. The parameters come from the mask of the subsystem. */
#include "common.c"
#include "im_current_vector.c"

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Lower limit (V) of the measured DC-bus voltage, which avoids the division by
 * zero in the PWM if the DC bus is not charged */
#define U_DC_MIN 1.0

static IMVectorControlSystem ctrl;

/* Initial state, restored while the control system is disabled */
static IMVectorControlSystem ctrl_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 1, 3, 1, 1};
static const int FEEDTHROUGH[] = {1, 1, 1, 1, 1};
static const int OUTPUT_WIDTHS[] = {3, 2, 2, 2, 4};
#define NUM_INPUTS 5
#define NUM_OUTPUTS 5
#define NUM_PARAMS 22

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(15, 0) * ParamDim(15, 1) != 1
        || !(ParamRealData(15, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(15, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    /* Check the parameters of the mask */
    if (PDIM(0) != 1) {
        SetErrorMessage("n_p must be a scalar.");
        return;
    }
    if (PDIM(1) != 1) {
        SetErrorMessage("R_s must be a scalar.");
        return;
    }
    if (PDIM(2) != 1) {
        SetErrorMessage("R_R must be a scalar.");
        return;
    }
    if (PDIM(3) != 1) {
        SetErrorMessage("L_sgm must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("L_M must be a scalar.");
        return;
    }
    if (PDIM(5) != 1) {
        SetErrorMessage("psi_s_nom must be a scalar.");
        return;
    }
    if (PDIM(6) != 1) {
        SetErrorMessage("i_s_max must be a scalar.");
        return;
    }
    if (PDIM(15) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }
    if (PDIM(16) != 1) {
        SetErrorMessage("speed_J must be a scalar.");
        return;
    }
    if (PDIM(17) != 1) {
        SetErrorMessage("speed_alpha_s must be a scalar.");
        return;
    }
    if (PDIM(20) != 1) {
        SetErrorMessage("pwm_t_d must be a scalar.");
        return;
    }
    if (PDIM(21) != 1) {
        SetErrorMessage("pwm_feedforward must be a scalar.");
        return;
    }

    /* Machine model parameters (InductionMachineInvGammaPars) */
    InductionMachineInvGammaPars par = {
        P(0, 0), P(1, 0), P(2, 0), P(3, 0), P(4, 0)};

    /* Current-vector controller configuration (CurrentVectorControllerCfg),
     * the defaults are used for empty parameters */
    IMCurrentVectorControllerCfg cfg = im_current_vector_controller_cfg(
        P(5, 0), P(6, 0));
    if (PDIM(7) > 0) {
        cfg.alpha_c = P(7, 0);
    }
    if (PDIM(8) > 0) {
        cfg.alpha_i = P(8, 0);
    }
    if (PDIM(9) > 0) {
        cfg.alpha_o = P(9, 0);
    }
    if (PDIM(10) > 0) {
        cfg.w_s_nom = P(10, 0);
    }
    if (PDIM(11) > 0) {
        cfg.k_u = P(11, 0);
    }
    if (PDIM(12) > 0) {
        cfg.k_fw = P(12, 0);
    }
    if (PDIM(13) > 0) {
        cfg.J = P(13, 0);
    }
    if (PDIM(14) > 0) {
        cfg.sensorless = P(14, 0);
    }
    if (PDIM(15) > 0) {
        cfg.T_s = P(15, 0);
    }

    /* Speed controller (SpeedController) */
    PIController speed_ctrl = speed_controller(
        P(16, 0), P(17, 0), PARAM(18),
        PDIM(19) > 0 ? P(19, 0) : INFINITY);

    im_vector_control_system_init(&ctrl, par, &cfg, speed_ctrl);

    /* Duty-ratio error model of the PWM (dead_time_error) */
    pwm_set_dead_time(&ctrl.pwm, P(20, 0), P(15, 0),
                      (int)P(21, 0));

    ctrl_init = ctrl;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: zero voltage, the control algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 3; k++) {
            OutputSignal(0, k) = 0.5;
        }
        OutputSignal(1, 0) = 0.0;
        OutputSignal(1, 1) = 0.0;
        OutputSignal(2, 0) = 0.0;
        OutputSignal(2, 1) = 0.0;
        OutputSignal(3, 0) = 0.0;
        OutputSignal(3, 1) = 0.0;
        OutputSignal(4, 0) = 0.0;
        OutputSignal(4, 1) = 0.0;
        OutputSignal(4, 2) = 0.0;
        OutputSignal(4, 3) = 0.0;
        return;
    }

    /* Measurements */
    double w_M_ref = InputSignal(1, 0);
    double i_s_abc[3] = {InputSignal(2, 0), InputSignal(2, 1),
                         InputSignal(2, 2)};
    double u_dc = fmax(InputSignal(3, 0), U_DC_MIN);
    IMMeasurements meas = {abc2complex(i_s_abc), u_dc, InputSignal(4, 0)};

    im_vector_control_system_compute_output(&ctrl, &meas, w_M_ref);

    /* Duty ratios, delayed by the Delay block outside the subsystem */
    for (int k = 0; k < 3; k++) {
        OutputSignal(0, k) = ctrl.ref.d_abc[k];
    }

    /* Monitored signals, the currents in estimated rotor flux coordinates */
    double complex rot = cexp(-I * carg(ctrl.fbk.psi_R));
    OutputSignal(1, 0) = ctrl.ref.w_M;
    OutputSignal(1, 1) = ctrl.fbk.w_M;
    OutputSignal(2, 0) = ctrl.ref.tau_M;
    OutputSignal(2, 1) = ctrl.fbk.tau_M;
    OutputSignal(3, 0) = cabs(ctrl.fbk.psi_s);
    OutputSignal(3, 1) = cabs(ctrl.fbk.psi_R);
    OutputSignal(4, 0) = creal(rot * ctrl.ref.i_s);
    OutputSignal(4, 1) = creal(rot * ctrl.fbk.i_s);
    OutputSignal(4, 2) = cimag(rot * ctrl.ref.i_s);
    OutputSignal(4, 3) = cimag(rot * ctrl.fbk.i_s);
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        ctrl = ctrl_init;
        return;
    }

    im_vector_control_system_update(&ctrl);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
