/*
 * sfun_im_2kw_cvc_control: Level-2 C MEX S-function generated by motulator_export
 * from the C-Script code of the PLECS model. The C-Script macros are
 * defined with the Simulink API. The state of the code is in static
 * variables, so a model can contain one instance of the block.
 *
 * Build with a C99 compiler with complex.h (gcc, clang, or MinGW-w64):
 *     mex sfun_im_2kw_cvc_control.c
 */

#define S_FUNCTION_NAME sfun_im_2kw_cvc_control
#define S_FUNCTION_LEVEL 2

#include "simstruc.h"

#define InputSignal(i, j) (ssGetInputPortRealSignal(S, (i))[j])
#define OutputSignal(i, j) (ssGetOutputPortRealSignal(S, (i))[j])
#define ParamRealData(i, j) (mxGetPr(ssGetSFcnParam(S, (i)))[j])
#define ParamDim(i, d)                                                           \
    ((int)((d) == 0 ? mxGetM(ssGetSFcnParam(S, (i)))                             \
                    : mxGetN(ssGetSFcnParam(S, (i)))))
#define SetErrorMessage(msg) ssSetErrorStatus(S, (msg))
#define ContState(i) (ssGetContStates(S)[i])
#define ContDeriv(i) (ssGetdX(S)[i])

/* Declarations of the C-Script (after simstruc.h, since complex.h
 * defines the macro I) */
/* Generated by motulator_export.plecs.im. The control algorithms are in the
 * included C files. The parameters come from the mask of the subsystem. */
/*
 * Common control functions and classes, ported from motulator. See common.h.
 */

/*
 * Common control functions and classes, ported from motulator.
 *
 * Python counterparts:
 *   motulator/common/utils/_utils.py        abc2complex, complex2abc, line2complex,
 *                                           wrap, clip, sign
 *   motulator/common/control/_controllers.py PIController, ComplexPIController
 *   motulator/common/control/_pwm.py         PWM (MPE overmodulation)
 *   motulator/common/utils/_dead_time.py     dead_time_error (with numpy.sign)
 *   motulator/drive/control/_common.py       SpeedController, SpeedObserver
 *
 * Complex space vectors use peak-value scaling, as in motulator.
 */

#ifndef MOTULATOR_COMMON_H
#define MOTULATOR_COMMON_H

#include <complex.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* Utility functions */
static double complex abc2complex(const double u[3]);
static void complex2abc(double complex u, double u_abc[3]);
/* Space vector from the line-to-line quantities u_ab and u_bc */
static double complex line2complex(const double u[2]);
static double wrap(double theta);
static double clip(double value, double min_value, double max_value);
static double sign(double x);

/* Lookup table with linear interpolation, equivalent to numpy.interp */
#define LUT_MAX_SIZE 64

typedef struct {
    int n;
    double x[LUT_MAX_SIZE]; /* Increasing sample points */
    double y[LUT_MAX_SIZE];
} LUT;

static double lut_interp(const LUT *lut, double x);

/* Brent's root finding in a bracketing interval, as scipy.optimize.brentq with the
 * default tolerances (used via scipy.optimize.root_scalar in motulator) */
typedef double (*ScalarFunction)(double x, void *data);

static double brentq(ScalarFunction f, double xa, double xb, void *data);

/* 2DOF PI controller */
typedef struct {
    double k_p;
    double k_t;
    double alpha_i; /* Inverse of the integration time */
    double u_max;
    /* States and workspace variables */
    double u_i;
    double v;
} PIController;

static void pi_init(PIController *self, double k_p, double k_t, double alpha_i,
                    double u_max);
static double pi_compute_output(PIController *self, double y_ref, double y,
                                double u_ff);
static void pi_update(PIController *self, double T_s, double u);

/* 2DOF synchronous-frame complex-vector PI controller */
typedef struct {
    double k_p;
    double k_t;
    double alpha_i; /* Inverse of the integration time */
    /* States and workspace variables */
    double complex u_i;
    double complex v;
} ComplexPIController;

static void complex_pi_init(ComplexPIController *self, double k_p, double k_i,
                            double k_t);
static double complex complex_pi_compute_output(ComplexPIController *self,
                                                double complex i_ref,
                                                double complex i,
                                                double complex u_ff);
static void complex_pi_update(ComplexPIController *self, double T_s,
                              double complex u, double w_c);

/* 2DOF PI speed controller (SpeedController); alpha_i = NAN means alpha_s */
static PIController speed_controller(double J, double alpha_s, double alpha_i,
                                     double tau_M_max);

/* Speed observer (mechanical system model is used if J > 0) */
typedef struct {
    double k_w;
    double k_tau;
    double J;
    /* States */
    double w_M;
    double tau_L;
} SpeedObserver;

static void speed_observer_init(SpeedObserver *self, double k_w, double k_tau,
                                double J);
static void speed_observer_update(SpeedObserver *self, double T_s, double eps,
                                  double tau_M);

/* Duty-ratio error due to the dead time t_d (dead_time_error with the signum
 * function), T_s being the half carrier period */
static void dead_time_error(const double i_abc[3], const double d_abc[3], double t_d,
                            double T_s, double d_err[3]);

/* Space-vector PWM with the minimum-phase-error (MPE) overmodulation. Optionally,
 * the duty-ratio error due to the dead time is modeled (pwm_set_dead_time), which
 * corresponds to d_err = dead_time_error(i_abc, d_abc, t_d, T_s) in motulator. */
typedef struct {
    double k_comp;
    double t_d;      /* Dead time of the duty-ratio error model, 0 = no error model */
    double T_s;      /* Sampling period of the duty-ratio error model */
    int feedforward; /* Compensate for the duty-ratio error */
    /* States */
    double complex realized_voltage;
    double complex old_u_c_ab;
    double d_abc[2][3]; /* Duty ratios of the two latest sampling periods */
} PWM;

static void pwm_init(PWM *self, double k_comp);
static void pwm_set_dead_time(PWM *self, double t_d, double T_s, int feedforward);
/* Realized voltage, corrected for the duty-ratio error using the measured current
 * (get_realized_voltage) */
static double complex pwm_realized_voltage(const PWM *self, double complex i_c_ab,
                                           double u_dc);
/* Duty ratios and the limited voltage reference; the measured current i_c_ab is
 * used in the feedforward compensation of the duty-ratio error */
static double complex pwm_compute_output(const PWM *self, double T_s,
                                         double complex u_c_ref_ab, double u_dc,
                                         double w, double complex i_c_ab,
                                         double d_abc[3]);
static void pwm_update(PWM *self, double complex u_c_ab, const double d_abc[3]);

#endif

/* Utility functions -------------------------------------------------------- */

static double complex abc2complex(const double u[3])
{
    return (2.0 / 3.0) * u[0] - (u[1] + u[2]) / 3.0 + I * (u[1] - u[2]) / sqrt(3.0);
}

static void complex2abc(double complex u, double u_abc[3])
{
    u_abc[0] = creal(u);
    u_abc[1] = 0.5 * (-creal(u) + sqrt(3.0) * cimag(u));
    u_abc[2] = 0.5 * (-creal(u) - sqrt(3.0) * cimag(u));
}

static double complex line2complex(const double u[2])
{
    return (2.0 * u[0] + u[1]) / 3.0 + I * u[1] / sqrt(3.0);
}

static double wrap(double theta)
{
    /* Limit the angle into the range [-pi, pi), as numpy.mod does */
    double x = fmod(theta + M_PI, 2.0 * M_PI);
    if (x < 0.0) {
        x += 2.0 * M_PI;
    }
    return x - M_PI;
}

static double clip(double value, double min_value, double max_value)
{
    return fmax(fmin(value, max_value), min_value);
}

static double sign(double x)
{
    return (x < 0.0) ? -1.0 : ((x > 0.0) ? 1.0 : 0.0);
}

static double lut_interp(const LUT *lut, double x)
{
    int n = lut->n;
    if (x <= lut->x[0]) {
        return lut->y[0];
    }
    if (x >= lut->x[n - 1]) {
        return lut->y[n - 1];
    }
    /* Binary search for the interval x[k] <= x < x[k + 1] */
    int lo = 0, hi = n - 1;
    while (hi - lo > 1) {
        int mid = (lo + hi) / 2;
        if (lut->x[mid] <= x) {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    double slope = (lut->y[hi] - lut->y[lo]) / (lut->x[hi] - lut->x[lo]);
    return slope * (x - lut->x[lo]) + lut->y[lo];
}

/* Port of scipy/optimize/Zeros/brentq.c with xtol = 2e-12, rtol = 4*eps, and
 * maxiter = 100 (the defaults of scipy.optimize.brentq). The function values at the
 * bracket ends must have opposite signs (or be zero). */
static double brentq(ScalarFunction f, double xa, double xb, void *data)
{
    const double xtol = 2e-12;
    const double rtol = 8.881784197001252e-16;
    const int iter = 100;
    double xpre = xa, xcur = xb;
    double xblk = 0.0, fblk = 0.0, spre = 0.0, scur = 0.0;
    double fpre = f(xpre, data);
    double fcur = f(xcur, data);

    if (fpre == 0.0) {
        return xpre;
    }
    if (fcur == 0.0) {
        return xcur;
    }
    if (signbit(fpre) == signbit(fcur)) {
        return NAN; /* No sign change */
    }
    for (int i = 0; i < iter; i++) {
        if (fpre != 0.0 && fcur != 0.0 && signbit(fpre) != signbit(fcur)) {
            xblk = xpre;
            fblk = fpre;
            spre = scur = xcur - xpre;
        }
        if (fabs(fblk) < fabs(fcur)) {
            xpre = xcur;
            xcur = xblk;
            xblk = xpre;
            fpre = fcur;
            fcur = fblk;
            fblk = fpre;
        }
        double delta = (xtol + rtol * fabs(xcur)) / 2.0;
        double sbis = (xblk - xcur) / 2.0;
        if (fcur == 0.0 || fabs(sbis) < delta) {
            return xcur;
        }
        if (fabs(spre) > delta && fabs(fcur) < fabs(fpre)) {
            double stry;
            if (xpre == xblk) {
                /* Interpolate */
                stry = -fcur * (xcur - xpre) / (fcur - fpre);
            } else {
                /* Extrapolate */
                double dpre = (fpre - fcur) / (xpre - xcur);
                double dblk = (fblk - fcur) / (xblk - xcur);
                stry = -fcur * (fblk * dblk - fpre * dpre) / (dblk * dpre * (fblk - fpre));
            }
            if (2.0 * fabs(stry) < fmin(fabs(spre), 3.0 * fabs(sbis) - delta)) {
                /* Good short step */
                spre = scur;
                scur = stry;
            } else {
                /* Bisect */
                spre = sbis;
                scur = sbis;
            }
        } else {
            /* Bisect */
            spre = sbis;
            scur = sbis;
        }
        xpre = xcur;
        fpre = fcur;
        if (fabs(scur) > delta) {
            xcur += scur;
        } else {
            xcur += (sbis > 0.0 ? delta : -delta);
        }
        fcur = f(xcur, data);
    }
    return xcur;
}

/* PIController ------------------------------------------------------------- */

static void pi_init(PIController *self, double k_p, double k_t, double alpha_i,
                    double u_max)
{
    self->k_p = k_p;
    self->k_t = k_t;
    self->alpha_i = alpha_i;
    self->u_max = u_max;
    self->u_i = 0.0;
    self->v = 0.0;
}

static double pi_compute_output(PIController *self, double y_ref, double y,
                                double u_ff)
{
    /* Estimate of a disturbance input */
    self->v = self->u_i - (self->k_p - self->k_t) * y + u_ff;
    double u = self->k_t * (y_ref - y) + self->v;
    /* Limit the controller output */
    return clip(u, -self->u_max, self->u_max);
}

static void pi_update(PIController *self, double T_s, double u)
{
    self->u_i += T_s * self->alpha_i * (u - self->v);
}

/* ComplexPIController ------------------------------------------------------ */

static void complex_pi_init(ComplexPIController *self, double k_p, double k_i,
                            double k_t)
{
    self->k_p = k_p;
    self->k_t = k_t;
    self->alpha_i = k_i / k_t;
    self->u_i = 0.0;
    self->v = 0.0;
}

static double complex complex_pi_compute_output(ComplexPIController *self,
                                                double complex i_ref,
                                                double complex i,
                                                double complex u_ff)
{
    /* Disturbance input estimate */
    self->v = self->u_i - (self->k_p - self->k_t) * i + u_ff;
    return self->k_t * (i_ref - i) + self->v;
}

static void complex_pi_update(ComplexPIController *self, double T_s,
                              double complex u, double w_c)
{
    self->u_i += T_s * (self->alpha_i + I * w_c) * (u - self->v);
}

/* SpeedController ---------------------------------------------------------- */

static PIController speed_controller(double J, double alpha_s, double alpha_i,
                                     double tau_M_max)
{
    PIController ctrl;
    alpha_i = isnan(alpha_i) ? alpha_s : alpha_i;
    double k_p = (alpha_s + alpha_i) * J;
    double k_i = alpha_s * alpha_i * J;
    double k_t = alpha_s * J;
    pi_init(&ctrl, k_p, k_t, k_i / k_t, tau_M_max);
    return ctrl;
}

/* SpeedObserver ------------------------------------------------------------ */

static void speed_observer_init(SpeedObserver *self, double k_w, double k_tau,
                                double J)
{
    self->k_w = k_w;
    self->k_tau = k_tau;
    self->J = J;
    self->w_M = 0.0;
    self->tau_L = 0.0;
}

static void speed_observer_update(SpeedObserver *self, double T_s, double eps,
                                  double tau_M)
{
    double d_w_M, d_tau_L;
    if (self->J <= 0.0) {
        d_w_M = self->k_w * eps;
        d_tau_L = 0.0;
    } else {
        d_w_M = (tau_M - self->tau_L) / self->J + self->k_w * eps;
        d_tau_L = -self->k_tau * eps;
    }
    self->w_M += T_s * d_w_M;
    self->tau_L += T_s * d_tau_L;
}

/* Dead time --------------------------------------------------------------- */

static void dead_time_error(const double i_abc[3], const double d_abc[3], double t_d,
                            double T_s, double d_err[3])
{
    for (int k = 0; k < 3; k++) {
        /* Switching-cycle averaged on-times of the upper and lower switches
         * (averaged_gate_signals) */
        double d = d_abc[k];
        double delta = (d > 0.0 && d < 1.0) ? t_d / (2.0 * T_s) : 0.0;
        double q_hi = fmax(d - delta, 0.0);
        double q_lo = fmax(1.0 - d - delta, 0.0);
        double b = 1.0 - q_hi - q_lo;
        d_err[k] = d - q_hi - 0.5 * b * (1.0 - sign(i_abc[k]));
    }
}

/* PWM ---------------------------------------------------------------------- */

static void pwm_init(PWM *self, double k_comp)
{
    self->k_comp = k_comp;
    self->t_d = 0.0;
    self->T_s = 0.0;
    self->feedforward = 1;
    self->realized_voltage = 0.0;
    self->old_u_c_ab = 0.0;
    for (int k = 0; k < 3; k++) {
        self->d_abc[0][k] = 0.0;
        self->d_abc[1][k] = 0.0;
    }
}

static void pwm_set_dead_time(PWM *self, double t_d, double T_s, int feedforward)
{
    self->t_d = t_d;
    self->T_s = T_s;
    self->feedforward = feedforward;
}

static double complex pwm_realized_voltage(const PWM *self, double complex i_c_ab,
                                           double u_dc)
{
    if (self->t_d <= 0.0) {
        return self->realized_voltage;
    }
    double i_abc[3], e0[3], e1[3], d_err[3];
    complex2abc(i_c_ab, i_abc);
    dead_time_error(i_abc, self->d_abc[0], self->t_d, self->T_s, e0);
    dead_time_error(i_abc, self->d_abc[1], self->t_d, self->T_s, e1);
    for (int k = 0; k < 3; k++) {
        d_err[k] = 0.5 * (e0[k] + e1[k]);
    }
    return self->realized_voltage - u_dc * abc2complex(d_err);
}

static void pwm_duty_ratios(double complex u_c_ref_ab, double u_dc, double d_abc[3])
{
    double u_abc[3];
    complex2abc(u_c_ref_ab, u_abc);

    /* Zero-sequence voltage resulting in space-vector PWM */
    double u_max = fmax(fmax(u_abc[0], u_abc[1]), u_abc[2]);
    double u_min = fmin(fmin(u_abc[0], u_abc[1]), u_abc[2]);
    double u_0 = 0.5 * (u_max + u_min);
    for (int k = 0; k < 3; k++) {
        u_abc[k] -= u_0;
    }

    /* MPE overmodulation */
    double m = (2.0 / u_dc) * fmax(fmax(u_abc[0], u_abc[1]), u_abc[2]);
    if (m > 1.0) {
        for (int k = 0; k < 3; k++) {
            u_abc[k] = u_abc[k] / m;
        }
    }

    /* Duty ratios */
    for (int k = 0; k < 3; k++) {
        d_abc[k] = fmax(fmin(u_abc[k] / u_dc + 0.5, 1.0), 0.0);
    }
}

static double complex pwm_compute_output(const PWM *self, double T_s,
                                         double complex u_c_ref_ab, double u_dc,
                                         double w, double complex i_c_ab,
                                         double d_abc[3])
{
    /* Advance the angle due to the computational and ZOH (PWM) delays */
    double theta_comp = self->k_comp * T_s * w;
    u_c_ref_ab = cexp(I * theta_comp) * u_c_ref_ab;

    /* Duty ratios */
    pwm_duty_ratios(u_c_ref_ab, u_dc, d_abc);

    /* Compensate for the duty-ratio error using the predicted currents */
    if (self->t_d > 0.0 && self->feedforward) {
        double i_c_abc[3], d_err[3];
        complex2abc(cexp(I * theta_comp) * i_c_ab, i_c_abc);
        dead_time_error(i_c_abc, d_abc, self->t_d, self->T_s, d_err);
        for (int k = 0; k < 3; k++) {
            d_abc[k] = clip(d_abc[k] + d_err[k], 0.0, 1.0);
        }
    }

    /* Limited voltage reference, including the compensation */
    return abc2complex(d_abc) * u_dc;
}

static void pwm_update(PWM *self, double complex u_c_ab, const double d_abc[3])
{
    self->realized_voltage = 0.5 * (self->old_u_c_ab + u_c_ab);
    self->old_u_c_ab = u_c_ab;
    for (int k = 0; k < 3; k++) {
        self->d_abc[0][k] = self->d_abc[1][k];
        self->d_abc[1][k] = d_abc[k];
    }
}
/*
 * Current-vector control of induction machine drives, ported from motulator. See
 * im_current_vector.h.
 */

/*
 * Current-vector control of induction machine drives, ported from motulator.
 *
 * Python counterparts:
 *   motulator/drive/utils/_parameters.py          InductionMachineInvGammaPars
 *   motulator/drive/control/_im_observers.py      FluxObserver, SpeedFluxObserver,
 *                                                 create_speed_flux_observer
 *   motulator/drive/control/_im_current_vector.py CurrentController,
 *                                                 CurrentReferenceGenerator,
 *                                                 CurrentVectorController
 *   motulator/drive/control/_base.py              VectorControlSystem
 *   motulator/drive/control/_common.py            SpeedController, SpeedObserver
 *
 * The machine model parameters are the constant inverse-Γ parameters, and the
 * default observer gains k_o of motulator are used. The control loop follows
 * motulator: the output function is free of side effects (apart from workspace
 * variables) and all states are updated in the update function, in the same order
 * as in motulator.
 */

#ifndef MOTULATOR_IM_CURRENT_VECTOR_H
#define MOTULATOR_IM_CURRENT_VECTOR_H


/* Constant inverse-Γ model parameters (InductionMachineInvGammaPars) */
typedef struct {
    double n_p;
    double R_s;
    double R_R;
    double L_sgm;
    double L_M;
} InductionMachineInvGammaPars;

/* Feedback signals for the control system (ObserverOutputs) */
typedef struct {
    double u_dc;          /* DC-bus voltage */
    double complex i_s;   /* Stator current */
    double complex u_s;   /* Stator voltage */
    double complex psi_s; /* Stator flux estimate */
    double complex psi_R; /* Rotor flux estimate */
    double tau_M;         /* Electromagnetic torque estimate */
    double tau_L;         /* Load torque estimate */
    double w_c;           /* Angular speed of the coordinate system */
    double w_s;           /* Synchronous angular frequency */
    double w_r;           /* Slip angular frequency estimate */
    double w_m;           /* Electrical angular rotor speed estimate */
    double w_M;           /* Mechanical angular rotor speed estimate */
    double theta_c;       /* Coordinate system angle */
    double complex e_o;   /* Estimation error */
    double eps;           /* Rotor speed error signal */
    double h;             /* Weight of the external speed error signal */
} IMObserverOutputs;

/* Reduced-order flux observer in synchronous coordinates (FluxObserver) */
typedef struct {
    InductionMachineInvGammaPars par;
    int sensorless; /* Selects the default observer gain k_o(w_m) */
    /* States */
    double complex psi_s;
    double theta_c;
    /* Other memory variables */
    double T_s_old;
    double complex old_i_s;
} IMFluxObserver;

typedef struct {
    SpeedObserver speed_observer;
    IMFluxObserver flux_observer;
} IMSpeedFluxObserver;

/* Current reference generator with field weakening (CurrentReferenceGenerator) */
typedef struct {
    InductionMachineInvGammaPars par;
    double i_s_max;
    double k_u;
    double i_sd_nom;
    double k_fw;
    double i_sd_ref; /* Integral state */
} IMCurrentReferenceGenerator;

/* Current-vector controller configuration (CurrentVectorControllerCfg). As in
 * motulator, the optional parameters default to None, represented here by NAN. The
 * observer gain k_o is the default of motulator. */
typedef struct {
    double psi_s_nom;
    double i_s_max;
    double alpha_c;
    double alpha_i;
    double alpha_o;
    double w_s_nom;
    double k_u;
    double k_fw; /* NAN or 0 = default */
    double J;
    int sensorless;
    double T_s;
} IMCurrentVectorControllerCfg;

typedef struct {
    double T_s;
    int sensorless;
    IMCurrentReferenceGenerator reference_gen;
    ComplexPIController current_ctrl;
    IMSpeedFluxObserver observer;
} IMCurrentVectorController;

/* Reference signals */
typedef struct {
    double T_s;
    double d_abc[3];
    double w_M;
    double tau_M;
    double complex i_s;
    double complex u_s;
    double complex u_c_ab; /* Limited converter voltage from the PWM */
} IMReferences;

/* Measured signals */
typedef struct {
    double complex i_c_ab; /* Converter current in stationary coordinates */
    double u_dc;
    double w_M; /* Mechanical rotor speed, used only in the sensored mode */
} IMMeasurements;

typedef struct {
    PWM pwm;
    IMCurrentVectorController vector_ctrl;
    PIController speed_ctrl;
    /* Workspace variables passed from the output to the update function */
    IMObserverOutputs fbk;
    IMReferences ref;
} IMVectorControlSystem;

static IMCurrentVectorControllerCfg im_current_vector_controller_cfg(double psi_s_nom,
                                                                     double i_s_max);

static void im_vector_control_system_init(IMVectorControlSystem *self,
                                          InductionMachineInvGammaPars par,
                                          const IMCurrentVectorControllerCfg *cfg,
                                          PIController speed_ctrl);
static void im_vector_control_system_compute_output(IMVectorControlSystem *self,
                                                    const IMMeasurements *meas,
                                                    double w_M_ref);
static void im_vector_control_system_update(IMVectorControlSystem *self);

#endif

/* Derived parameters (properties of InductionMachineInvGammaPars) */
static double im_alpha(const InductionMachineInvGammaPars *par)
{
    return par->R_R / par->L_M;
}

static double im_w_rb(const InductionMachineInvGammaPars *par)
{
    return (par->L_sgm > 0.0) ? par->R_R * (1.0 / par->L_sgm + 1.0 / par->L_M) : 0.0;
}

/* Configuration ------------------------------------------------------------ */

static IMCurrentVectorControllerCfg im_current_vector_controller_cfg(double psi_s_nom,
                                                                     double i_s_max)
{
    IMCurrentVectorControllerCfg cfg;
    cfg.psi_s_nom = psi_s_nom;
    cfg.i_s_max = i_s_max;
    cfg.alpha_c = 2.0 * M_PI * 200.0;
    cfg.alpha_i = NAN;
    cfg.alpha_o = NAN;
    cfg.w_s_nom = 2.0 * M_PI * 50.0;
    cfg.k_u = 0.95;
    cfg.k_fw = NAN;
    cfg.J = NAN;
    cfg.sensorless = 1;
    cfg.T_s = 125e-6;
    return cfg;
}

/* IMFluxObserver ----------------------------------------------------------- */

static void im_flux_observer_init(IMFluxObserver *self,
                                  InductionMachineInvGammaPars par, int sensorless)
{
    self->par = par;
    self->sensorless = sensorless;
    self->psi_s = 0.0;
    self->theta_c = 0.0;
    self->T_s_old = 0.0;
    self->old_i_s = 0.0;
}

/* Default observer gain of create_speed_flux_observer */
static double complex im_observer_gain(const IMFluxObserver *self, double w_m)
{
    double alpha = im_alpha(&self->par);
    if (self->sensorless) {
        return (0.5 * alpha + 0.2 * fabs(w_m)) / (alpha - I * w_m);
    }
    return 1.0 + 0.2 * fabs(w_m) / (alpha - I * w_m);
}

static void im_flux_observer_compute_output(const IMFluxObserver *self,
                                            double complex u_s_ab,
                                            double complex i_s_ab, double w_M,
                                            double eps_ext, double h,
                                            IMObserverOutputs *out)
{
    /* The weight h of the external speed error signal eps_ext selects between the
     * sensorless (h = 0) and sensored (h = 1) modes */
    const InductionMachineInvGammaPars *par = &self->par;
    out->psi_s = self->psi_s;
    out->theta_c = self->theta_c;
    out->h = h;

    /* Current and voltage vectors in estimated rotor flux coordinates */
    out->i_s = cexp(-I * out->theta_c) * i_s_ab;
    out->u_s = cexp(-I * out->theta_c) * u_s_ab;

    /* Mechanical and electrical angular speeds of the rotor */
    out->w_M = w_M;
    out->w_m = par->n_p * w_M;

    /* Rotor flux estimate */
    out->psi_R = out->psi_s - par->L_sgm * self->old_i_s;

    /* Slip angular frequency */
    double complex prod = out->psi_s * conj(out->psi_R);
    out->w_r = (creal(prod) > 0.0) ? im_w_rb(par) * cimag(prod) / creal(prod) : 0.0;

    /* Angular speed of the coordinate system equals synchronous angular frequency */
    out->w_c = out->w_s = out->w_m + out->w_r;

    /* Estimation error */
    double complex d_i_s =
        (self->T_s_old > 0.0) ? (out->i_s - self->old_i_s) / self->T_s_old : 0.0;
    double R_sgm = par->R_s + par->R_R;
    out->e_o = par->L_sgm * d_i_s - out->u_s +
               (R_sgm + I * out->w_c * par->L_sgm) * out->i_s -
               (im_alpha(par) - I * out->w_m) * out->psi_R;

    /* Torque estimate */
    out->tau_M =
        (par->L_sgm > 0.0) ? 1.5 * par->n_p * cimag(out->i_s * conj(out->psi_s)) : 0.0;

    /* Rotor speed error signal for the speed observer. The model-based part is
     * faded out as the external error signal takes over. */
    double eps_o =
        (cabs(out->psi_R) > 0.0) ? -cimag(out->e_o / out->psi_R) / par->n_p : 0.0;
    out->eps = h * eps_ext + (1.0 - h) * eps_o;
}

static void im_flux_observer_update(IMFluxObserver *self, double T_s,
                                    const IMObserverOutputs *out)
{
    const InductionMachineInvGammaPars *par = &self->par;

    /* Observer gains. The conjugate-error gain is faded out together with the
     * model-based error signal. */
    double complex k_o1 = im_observer_gain(self, out->w_m);
    double complex proj =
        (cabs(out->psi_R) > 0.0) ? out->psi_R / conj(out->psi_R) : 0.0;
    double complex k_o2 = (1.0 - out->h) * k_o1 * proj;

    /* Update the states */
    double complex v_err = k_o1 * out->e_o + k_o2 * conj(out->e_o);
    double complex d_psi_s =
        out->u_s - par->R_s * out->i_s - I * out->w_c * out->psi_s + v_err;
    self->psi_s += T_s * d_psi_s;
    self->theta_c = wrap(self->theta_c + T_s * out->w_c);

    /* Sampling period and current for the next sampling period */
    self->T_s_old = T_s;
    self->old_i_s = out->i_s;
}

/* IMSpeedFluxObserver ------------------------------------------------------ */

static void im_speed_flux_observer_init(IMSpeedFluxObserver *self,
                                        InductionMachineInvGammaPars par,
                                        double alpha_o, int sensorless, double J)
{
    /* Observer gains for critically damped dynamics */
    double k_w, k_tau;
    if (J <= 0.0) {
        k_w = alpha_o;
        k_tau = 0.0;
    } else {
        k_w = 2.0 * alpha_o;
        k_tau = J * alpha_o * alpha_o;
    }
    speed_observer_init(&self->speed_observer, k_w, k_tau, J);
    im_flux_observer_init(&self->flux_observer, par, sensorless);
}

static void im_speed_flux_observer_compute_output(const IMSpeedFluxObserver *self,
                                                  double complex u_s_ab,
                                                  double complex i_s_ab,
                                                  double eps_ext, double h,
                                                  IMObserverOutputs *out)
{
    double w_M = self->speed_observer.w_M;
    double tau_L = self->speed_observer.tau_L;
    im_flux_observer_compute_output(&self->flux_observer, u_s_ab, i_s_ab, w_M,
                                    eps_ext, h, out);
    out->tau_L = tau_L;
}

static void im_speed_flux_observer_update(IMSpeedFluxObserver *self, double T_s,
                                          const IMObserverOutputs *out)
{
    speed_observer_update(&self->speed_observer, T_s, out->eps, out->tau_M);
    im_flux_observer_update(&self->flux_observer, T_s, out);
}

/* IMCurrentReferenceGenerator ---------------------------------------------- */

static void im_reference_gen_init(IMCurrentReferenceGenerator *self,
                                  InductionMachineInvGammaPars par, double psi_s_nom,
                                  double i_s_max, double w_s_nom, double k_u,
                                  double k_fw)
{
    self->par = par;
    self->i_s_max = i_s_max;
    self->k_u = k_u;
    self->i_sd_nom = psi_s_nom / (par.L_M + par.L_sgm);
    if (isnan(k_fw) || k_fw == 0.0) {
        k_fw = 2.0 * par.R_R / (w_s_nom * par.L_sgm * par.L_sgm);
    }
    self->k_fw = k_fw;
    self->i_sd_ref = self->i_sd_nom;
}

static void im_reference_gen_compute_output(const IMCurrentReferenceGenerator *self,
                                            double tau_M_ref, double psi_R,
                                            double complex *i_s_ref,
                                            double *tau_M_ref_lim)
{
    const InductionMachineInvGammaPars *par = &self->par;
    double i_sd_ref = self->i_sd_ref;

    /* q-axis current reference */
    double i_sq_ref = (psi_R > 0.0) ? tau_M_ref / (1.5 * par->n_p * psi_R) : 0.0;

    /* q-axis current limit: priority given to the d component, and the breakdown
     * torque limit */
    double i_sq_max1 = sqrt(self->i_s_max * self->i_s_max - i_sd_ref * i_sd_ref);
    double i_sq_max2 = psi_R / par->L_sgm + i_sd_ref;
    double i_sq_max = fmin(i_sq_max1, i_sq_max2);
    i_sq_ref = clip(i_sq_ref, -i_sq_max, i_sq_max);

    *i_s_ref = i_sd_ref + I * i_sq_ref;

    /* Limited torque (for the speed controller) */
    *tau_M_ref_lim = 1.5 * par->n_p * psi_R * i_sq_ref;
}

static void im_reference_gen_update(IMCurrentReferenceGenerator *self, double T_s,
                                    double complex u_s_ref, double u_dc)
{
    /* Field weakening based on the unlimited reference voltage */
    double u_s_max = self->k_u * u_dc / sqrt(3.0);
    self->i_sd_ref += T_s * self->k_fw * (u_s_max - cabs(u_s_ref));
    self->i_sd_ref = clip(self->i_sd_ref, -self->i_s_max, self->i_sd_nom);
}

/* IMCurrentVectorController ------------------------------------------------ */

static void im_current_vector_ctrl_init(IMCurrentVectorController *self,
                                        InductionMachineInvGammaPars par,
                                        const IMCurrentVectorControllerCfg *cfg)
{
    /* Resolve the defaults, as in CurrentVectorControllerCfg.__post_init__ and
     * CurrentVectorController.__init__ */
    double alpha_i = isnan(cfg->alpha_i) ? cfg->alpha_c : cfg->alpha_i;
    double J = isnan(cfg->J) ? 0.0 : cfg->J; /* Zero means None */
    double alpha_o = cfg->alpha_o;
    if (isnan(alpha_o)) {
        double alpha = 2.0 * M_PI * 60.0;
        alpha_o = (J > 0.0) ? 0.5 * alpha : alpha;
    }

    self->T_s = cfg->T_s;
    self->sensorless = cfg->sensorless;
    im_reference_gen_init(&self->reference_gen, par, cfg->psi_s_nom, cfg->i_s_max,
                          cfg->w_s_nom, cfg->k_u, cfg->k_fw);
    /* CurrentController: 2DOF PI gains from the bandwidths and the leakage
     * inductance */
    double k_t = cfg->alpha_c * par.L_sgm;
    double k_i = cfg->alpha_c * alpha_i * par.L_sgm;
    double k_p = (cfg->alpha_c + alpha_i) * par.L_sgm;
    complex_pi_init(&self->current_ctrl, k_p, k_i, k_t);
    im_speed_flux_observer_init(&self->observer, par, alpha_o, cfg->sensorless, J);
}

static void im_current_vector_ctrl_compute_output(IMCurrentVectorController *self,
                                                  double tau_M_ref,
                                                  const IMObserverOutputs *fbk,
                                                  IMReferences *ref)
{
    ref->T_s = self->T_s;
    im_reference_gen_compute_output(&self->reference_gen, tau_M_ref,
                                    cabs(fbk->psi_R), &ref->i_s, &ref->tau_M);
    /* Transform the reference to the same coordinates as the feedback */
    ref->i_s = cexp(I * carg(fbk->psi_R)) * ref->i_s;
    ref->u_s = complex_pi_compute_output(&self->current_ctrl, ref->i_s, fbk->i_s, 0.0);
}

static void im_current_vector_ctrl_update(IMCurrentVectorController *self,
                                          const IMReferences *ref,
                                          const IMObserverOutputs *fbk)
{
    im_speed_flux_observer_update(&self->observer, ref->T_s, fbk);
    im_reference_gen_update(&self->reference_gen, ref->T_s, ref->u_s, fbk->u_dc);
    complex_pi_update(&self->current_ctrl, ref->T_s, fbk->u_s, fbk->w_c);
}

/* IMVectorControlSystem ---------------------------------------------------- */

static void im_vector_control_system_init(IMVectorControlSystem *self,
                                          InductionMachineInvGammaPars par,
                                          const IMCurrentVectorControllerCfg *cfg,
                                          PIController speed_ctrl)
{
    pwm_init(&self->pwm, 1.5);
    im_current_vector_ctrl_init(&self->vector_ctrl, par, cfg);
    self->speed_ctrl = speed_ctrl;
    self->speed_ctrl.u_i = 0.0;
    self->speed_ctrl.v = 0.0;
}

static void im_vector_control_system_compute_output(IMVectorControlSystem *self,
                                                    const IMMeasurements *meas,
                                                    double w_M_ref)
{
    IMObserverOutputs *fbk = &self->fbk;
    IMReferences *ref = &self->ref;

    /* Feedback signals */
    double complex u_c_ab = pwm_realized_voltage(&self->pwm, meas->i_c_ab, meas->u_dc);
    const IMSpeedFluxObserver *observer = &self->vector_ctrl.observer;
    if (self->vector_ctrl.sensorless) {
        im_speed_flux_observer_compute_output(observer, u_c_ab, meas->i_c_ab, 0.0,
                                              0.0, fbk);
    } else {
        /* Speed error from the measured rotor speed */
        double eps = meas->w_M - observer->speed_observer.w_M;
        im_speed_flux_observer_compute_output(observer, u_c_ab, meas->i_c_ab, eps,
                                              1.0, fbk);
    }
    fbk->u_dc = meas->u_dc;

    /* Speed controller and vector controller */
    double tau_M_ref = pi_compute_output(&self->speed_ctrl, w_M_ref, fbk->w_M, 0.0);
    im_current_vector_ctrl_compute_output(&self->vector_ctrl, tau_M_ref, fbk, ref);

    /* Duty ratios for the PWM */
    double complex u_s_ab_ref = cexp(I * fbk->theta_c) * ref->u_s;
    ref->u_c_ab = pwm_compute_output(&self->pwm, ref->T_s, u_s_ab_ref, fbk->u_dc,
                                     fbk->w_c, meas->i_c_ab, ref->d_abc);
    ref->w_M = w_M_ref;
}

static void im_vector_control_system_update(IMVectorControlSystem *self)
{
    pwm_update(&self->pwm, self->ref.u_c_ab, self->ref.d_abc);
    im_current_vector_ctrl_update(&self->vector_ctrl, &self->ref, &self->fbk);
    pi_update(&self->speed_ctrl, self->ref.T_s, self->ref.tau_M);
}

#define P(i, j) ParamRealData(i, j)
#define PDIM(i) (ParamDim(i, 0) * ParamDim(i, 1))

/* Parameter value, or NAN for an empty parameter (None in motulator) */
#define PARAM(i) (PDIM(i) > 0 ? P(i, 0) : NAN)

/* Lower limit (V) of the measured DC-bus voltage, which avoids the division by
 * zero in the PWM if the DC bus is not charged */
#define U_DC_MIN 1.0

static IMVectorControlSystem ctrl;

/* Initial state, restored while the control system is disabled */
static IMVectorControlSystem ctrl_init;

/* Ports and parameters of the C-Script */
static const int INPUT_WIDTHS[] = {1, 1, 3, 1, 1};
static const int FEEDTHROUGH[] = {1, 1, 1, 1, 1};
static const int OUTPUT_WIDTHS[] = {3, 2, 2, 2, 4};
#define NUM_INPUTS 5
#define NUM_OUTPUTS 5
#define NUM_PARAMS 22

static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NUM_PARAMS);
    ssSetNumContStates(S, 0);
    ssSetNumDiscStates(S, 0);
    if (!ssSetNumInputPorts(S, NUM_INPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_INPUTS; k++) {
        ssSetInputPortWidth(S, k, INPUT_WIDTHS[k]);
        ssSetInputPortDirectFeedThrough(S, k, FEEDTHROUGH[k]);
        ssSetInputPortRequiredContiguous(S, k, 1);
    }
    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) {
        return;
    }
    for (int k = 0; k < NUM_OUTPUTS; k++) {
        ssSetOutputPortWidth(S, k, OUTPUT_WIDTHS[k]);
    }
    ssSetNumSampleTimes(S, 1);
    ssSetOptions(S, SS_OPTION_EXCEPTION_FREE_CODE);
#if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Reported by Simulink */
    }
    for (int k = 0; k < NUM_PARAMS; k++) {
        const mxArray *p = ssGetSFcnParam(S, k);
        if (!mxIsDouble(p) || mxIsComplex(p)) {
            SetErrorMessage(
                "The parameters must be real double arrays.");
            return;
        }
        ssSetSFcnParamTunable(S, k, SS_PRM_NOT_TUNABLE);
    }
    if (ParamDim(15, 0) * ParamDim(15, 1) != 1
        || !(ParamRealData(15, 0) > 0.0)) {
        SetErrorMessage("The sampling period must be a positive scalar.");
        return;
    }
#endif
}

static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, ParamRealData(15, 0));
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_START
static void mdlStart(SimStruct *S)
{
    /* Check the parameters of the mask */
    if (PDIM(0) != 1) {
        SetErrorMessage("n_p must be a scalar.");
        return;
    }
    if (PDIM(1) != 1) {
        SetErrorMessage("R_s must be a scalar.");
        return;
    }
    if (PDIM(2) != 1) {
        SetErrorMessage("R_R must be a scalar.");
        return;
    }
    if (PDIM(3) != 1) {
        SetErrorMessage("L_sgm must be a scalar.");
        return;
    }
    if (PDIM(4) != 1) {
        SetErrorMessage("L_M must be a scalar.");
        return;
    }
    if (PDIM(5) != 1) {
        SetErrorMessage("psi_s_nom must be a scalar.");
        return;
    }
    if (PDIM(6) != 1) {
        SetErrorMessage("i_s_max must be a scalar.");
        return;
    }
    if (PDIM(15) != 1) {
        SetErrorMessage("T_s must be a scalar.");
        return;
    }
    if (PDIM(16) != 1) {
        SetErrorMessage("speed_J must be a scalar.");
        return;
    }
    if (PDIM(17) != 1) {
        SetErrorMessage("speed_alpha_s must be a scalar.");
        return;
    }
    if (PDIM(20) != 1) {
        SetErrorMessage("pwm_t_d must be a scalar.");
        return;
    }
    if (PDIM(21) != 1) {
        SetErrorMessage("pwm_feedforward must be a scalar.");
        return;
    }

    /* Machine model parameters (InductionMachineInvGammaPars) */
    InductionMachineInvGammaPars par = {
        P(0, 0), P(1, 0), P(2, 0), P(3, 0), P(4, 0)};

    /* Current-vector controller configuration (CurrentVectorControllerCfg),
     * the defaults are used for empty parameters */
    IMCurrentVectorControllerCfg cfg = im_current_vector_controller_cfg(
        P(5, 0), P(6, 0));
    if (PDIM(7) > 0) {
        cfg.alpha_c = P(7, 0);
    }
    if (PDIM(8) > 0) {
        cfg.alpha_i = P(8, 0);
    }
    if (PDIM(9) > 0) {
        cfg.alpha_o = P(9, 0);
    }
    if (PDIM(10) > 0) {
        cfg.w_s_nom = P(10, 0);
    }
    if (PDIM(11) > 0) {
        cfg.k_u = P(11, 0);
    }
    if (PDIM(12) > 0) {
        cfg.k_fw = P(12, 0);
    }
    if (PDIM(13) > 0) {
        cfg.J = P(13, 0);
    }
    if (PDIM(14) > 0) {
        cfg.sensorless = P(14, 0);
    }
    if (PDIM(15) > 0) {
        cfg.T_s = P(15, 0);
    }

    /* Speed controller (SpeedController) */
    PIController speed_ctrl = speed_controller(
        P(16, 0), P(17, 0), PARAM(18),
        PDIM(19) > 0 ? P(19, 0) : INFINITY);

    im_vector_control_system_init(&ctrl, par, &cfg, speed_ctrl);

    /* Duty-ratio error model of the PWM (dead_time_error) */
    pwm_set_dead_time(&ctrl.pwm, P(20, 0), P(15, 0),
                      (int)P(21, 0));

    ctrl_init = ctrl;
}

static void mdlOutputs(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: zero voltage, the control algorithm is not run */
    if (!(InputSignal(0, 0) > 0.0)) {
        for (int k = 0; k < 3; k++) {
            OutputSignal(0, k) = 0.5;
        }
        OutputSignal(1, 0) = 0.0;
        OutputSignal(1, 1) = 0.0;
        OutputSignal(2, 0) = 0.0;
        OutputSignal(2, 1) = 0.0;
        OutputSignal(3, 0) = 0.0;
        OutputSignal(3, 1) = 0.0;
        OutputSignal(4, 0) = 0.0;
        OutputSignal(4, 1) = 0.0;
        OutputSignal(4, 2) = 0.0;
        OutputSignal(4, 3) = 0.0;
        return;
    }

    /* Measurements */
    double w_M_ref = InputSignal(1, 0);
    double i_s_abc[3] = {InputSignal(2, 0), InputSignal(2, 1),
                         InputSignal(2, 2)};
    double u_dc = fmax(InputSignal(3, 0), U_DC_MIN);
    IMMeasurements meas = {abc2complex(i_s_abc), u_dc, InputSignal(4, 0)};

    im_vector_control_system_compute_output(&ctrl, &meas, w_M_ref);

    /* Duty ratios, delayed by the Delay block outside the subsystem */
    for (int k = 0; k < 3; k++) {
        OutputSignal(0, k) = ctrl.ref.d_abc[k];
    }

    /* Monitored signals, the currents in estimated rotor flux coordinates */
    double complex rot = cexp(-I * carg(ctrl.fbk.psi_R));
    OutputSignal(1, 0) = ctrl.ref.w_M;
    OutputSignal(1, 1) = ctrl.fbk.w_M;
    OutputSignal(2, 0) = ctrl.ref.tau_M;
    OutputSignal(2, 1) = ctrl.fbk.tau_M;
    OutputSignal(3, 0) = cabs(ctrl.fbk.psi_s);
    OutputSignal(3, 1) = cabs(ctrl.fbk.psi_R);
    OutputSignal(4, 0) = creal(rot * ctrl.ref.i_s);
    OutputSignal(4, 1) = creal(rot * ctrl.fbk.i_s);
    OutputSignal(4, 2) = cimag(rot * ctrl.ref.i_s);
    OutputSignal(4, 3) = cimag(rot * ctrl.fbk.i_s);
}

#define MDL_UPDATE
static void mdlUpdate(SimStruct *S, int_T tid)
{
    UNUSED_ARG(tid);
    /* Disabled: reset the state */
    if (!(InputSignal(0, 0) > 0.0)) {
        ctrl = ctrl_init;
        return;
    }

    im_vector_control_system_update(&ctrl);
}

static void mdlTerminate(SimStruct *S)
{
    UNUSED_ARG(S);
}

#ifdef MATLAB_MEX_FILE
#include "simulink.c"
#else
#include "cg_sfun.h"
#endif
