"""
Export grid converter systems to Simulink.

This module writes a Simulink model of a motulator grid converter system with
grid-following or grid-forming control, in the same way as
`motulator_export.plecs.grid` writes a PLECS model. The control system is the
C-Script code of the PLECS model wrapped in an S-function. The system model is built
from basic Simulink blocks by `build_grid.m`: the AC filter (an LCL filter, or an L
filter with the grid inductance) is modeled with space vectors in stationary
coordinates, and the grid voltage is generated by Sine Wave blocks.

Currently supported: the grid converter systems and control systems of
`motulator_export.plecs.grid`.

"""

from pathlib import Path
from typing import Any, cast

import numpy as np
from motulator.grid.control import GridConverterControlSystem
from motulator.grid.model import GridConverterSystem, LCLFilter

from motulator_export.plecs import grid
from motulator_export.plecs._common import StepSignal
from motulator_export.plecs._schematic import _fmt
from motulator_export.simulink._common import (
    _m_source,
    _m_steps,
    scope_indices,
    write_script,
)
from motulator_export.simulink._common import simulate as _simulate


def _plant_variables(mdl: GridConverterSystem) -> list[tuple[str, Any]]:
    """Workspace variables of the system model, see `grid._plant_variables`."""
    # The initial capacitor voltage as a space vector [real imag]
    variables = []
    for name, value in grid._plant_variables(mdl):
        if name == "ac_filter.u_f0_abc":
            u_f0_ab = cast(LCLFilter, mdl.ac_filter).state.u_f_ab
            variables.append(("ac_filter.u_f0_ab", [u_f0_ab.real, u_f0_ab.imag]))
        else:
            variables.append((name, value))
    return variables


def write_model(
    path: str | Path,
    mdl: GridConverterSystem,
    ctrl: GridConverterControlSystem,
    t_stop: float,
    p_g_ref: StepSignal,
    q_g_ref: StepSignal | None = None,
    v_c_ref: float | None = None,
    enable: StepSignal | float = 1.0,
) -> Path:
    """
    Write a MATLAB script that builds the Simulink model of the grid converter system.

    Running the script in MATLAB compiles the S-function and saves the model (and
    the compiled S-function) in the folder of the script.

    Parameters
    ----------
    path : str | Path
        Path of the model (.slx). The script is written in the same folder, named
        `build_<model>.m`, with the source of the S-function.
    mdl : GridConverterSystem
        Continuous-time system model.
    ctrl : GridConverterControlSystem
        Discrete-time control system.
    t_stop : float
        Simulation stop time (s).
    p_g_ref : StepSignal
        Active power reference (W).
    q_g_ref : StepSignal, optional
        Reactive power reference (VAr), needed in grid-following control.
    v_c_ref : float, optional
        Converter voltage magnitude reference (V), needed in grid-forming control.

    Returns
    -------
    Path
        Path of the written script.

    """
    path = Path(path)
    grid._check_supported(mdl, ctrl)
    block, values = grid._control_block(ctrl)
    refs: list[list[Any]] = [
        [
            "enable",
            "step" if isinstance(enable, StepSignal) else "constant",
            _m_source(enable),
        ],
        ["p_g_ref", "step", _m_steps(p_g_ref)],
    ]
    if block is grid.GFL_BLOCK:
        if q_g_ref is None:
            raise ValueError("q_g_ref is needed in grid-following control")
        refs.append(["q_g_ref", "step", _m_steps(q_g_ref)])
    else:
        if v_c_ref is None:
            raise ValueError("v_c_ref is needed in grid-forming control")
        refs.append(["v_c_ref", "constant", float(v_c_ref)])
    # Scope: the powers, the converter currents, and the other monitored signals
    groups = list(block.outputs.items())
    scope = [("Power", [f"ctrl.{n}" for n in groups[0][1]])]
    scope += [("Converter current", ["mdl.i_c_a", "mdl.i_c_b", "mdl.i_c_c"])]
    scope += [(name.split(" (")[0], [f"ctrl.{n}" for n in s]) for name, s in groups[1:]]
    init = "".join(f"{n} = {_fmt(v)};\n" for n, v in _plant_variables(mdl))
    fields = [
        ("init", init),
        ("ac_filter", "lcl" if isinstance(mdl.ac_filter, LCLFilter) else "l"),
        ("refs", refs),
        ("scope", scope_indices(scope, grid._mdl_outputs(mdl), block.signals)),
    ]
    return write_script(
        path, block, values, fields, "build_grid", values["T_s"], t_stop
    )


def simulate(
    path: str | Path,
    t_eval: np.ndarray,
    mdl: GridConverterSystem,
    ctrl: GridConverterControlSystem,
    build: bool = True,
) -> tuple[dict[str, np.ndarray], dict[str, np.ndarray]]:
    """
    Simulate the Simulink model via the MATLAB Engine API for Python.

    Parameters
    ----------
    path : str | Path
        Path of the model (.slx).
    t_eval : ndarray
        Output times (s).
    mdl : GridConverterSystem
        System model, which defines the signals of the output port "mdl".
    ctrl : GridConverterControlSystem
        Control system, which defines the monitored signals.
    build : bool, optional
        Run the build script `build_<model>.m` first, defaults to True.

    Returns
    -------
    mdl : dict[str, ndarray]
        Converter (and grid) phase currents and the time "t".
    ctrl : dict[str, ndarray]
        Monitored signals of the control system and the time "t".

    """
    block, _ = grid._control_block(ctrl)
    return _simulate(path, t_eval, grid._mdl_outputs(mdl), block.signals, build)
